version: '3'

services:
  index:
    build:
      context: .
      dockerfile: ./compose/local/index/Dockerfile
    image: docker.qabel.de/qabel-index-dev
    env_file:
      - ./.envs/.local/.index
      - ./.envs/.local/.postgres
    command: /start
