version: '3'

services:
  index:
    build:
      context: .
      dockerfile: ./compose/production/index/Dockerfile
    image: docker.qabel.de/qabel-index

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: docker.qabel.de/qabel-postgres
