version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  index:
    build:
      context: .
      dockerfile: ./compose/production/index/Dockerfile
    image: docker.qabel.de/qabel-index
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.index
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: docker.qabel.de/qabel-index-postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - index
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: redis:5.0
