# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('email', 'E-Mail address'), ('phone', 'phone number')], db_index=True, max_length=30)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=255)),
                ('drop_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingUpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_json_request', models.TextField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_service.PendingUpdateRequest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together=set([('public_key', 'alias', 'drop_url')]),
        ),
        migrations.AlterIndexTogether(
            name='identity',
            index_together=set([('public_key', 'alias', 'drop_url')]),
        ),
        migrations.AddField(
            model_name='entry',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_service.Identity'),
        ),
        migrations.AlterIndexTogether(
            name='entry',
            index_together=set([('field', 'value')]),
        ),
    ]
