# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_service', '0003_singular_data_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='field',
            field=models.CharField(choices=[('email', 'E-Mail address'), ('phone', 'Phone number')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='identity',
            name='public_key',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='identity',
            index_together=set([]),
        ),
    ]
