"""
Django settings for qabel_index project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import datetime
import os
import environ

env = environ.Env()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', [])

DEBUG = env.bool("DJANGO_DEBUG", False)

DATABASES = {"default": env.db("DATABASE_URL")}

# https://docs.djangoproject.com/en/dev/ref/settings/#secret-key
SECRET_KEY = env("DJANGO_SECRET_KEY")

EMAIL_CONFIG = env.email_url('DJANGO_EMAIL_URL')
vars().update(EMAIL_CONFIG)

# Enable shallow verification, i.e. do not confirm via verification mails or SMSes.
FACET_SHALLOW_VERIFICATION = env.bool('INDEX_SHALLOW_VERIFICATION', False)

# Application definition

INSTALLED_APPS = (
    'qabel_web_theme',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_prometheus',
    'rest_framework',
    'sendsms',
    'bootstrapform',
    'index_service',
)

MIDDLEWARE= (
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# https://docs.djangoproject.com/en/1.8/topics/i18n/


from django.utils.translation import ugettext_lazy as _

LANGUAGE_CODE = 'de-DE'
LANGUAGES = (
    ('de', _('German')),
    ('en', _('English')),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Application configuration

PROMETHEUS_EXPORT_MIGRATIONS = False

REQUIRE_AUTHORIZATION = False
ACCOUNTING_APISECRET = env('INDEX_API_SECRET')
ACCOUNTING_URL = env('INDEX_ACCOUNTING_HOST')

# Pending update requests expire after this time interval
PENDING_REQUEST_MAX_AGE = datetime.timedelta(days=3)

SERVER_PRIVATE_KEY = '247a1db50f8747f0e5e1f755c4390a598d36a4c7af202c2234b0613645d9c22a'

SENDSMS_DEFAULT_FROM_PHONE = '+15005550006'

# https://en.wikipedia.org/wiki/List_of_country_calling_codes
SMS_BLACKLISTED_COUNTRIES = (
    # Cuba
    53,
    # Iran
    98,
    # Best korea
    850,
    # Sudan
    249,
    # Syria
    963,

    # France
    33,
        # Guadeloupe (including Saint Barthélemy, Saint Martin)
        590,

        # French Guiana
        594,

        # Martinique
        596,

        # Reunion + Mayotte
        262,

        # Saint Pierre and Miquelon
        508,

        # Wallis and Futuna
        681,

        # French Polynesia
        689,

        # New Caledonia,
        687,

    # Egypt
    20,

    # Armenia
    374,

    # Azerbaijan
    994,

    # Burundi
    257,

    # Ivory coast
    225,

    # Eritrea
    291,

    # Guinea
    224,

    # Guinea-Bissau
    245,

    # Iraq
    964,

    # Yemen
    967,

    # Congo
    242,

    # Lebanon
    961,

    # Liberia
    231,

    # Libya
    218,

    # Myanmar
    95,

    # Sierra Leone
    232,

    # Zimbabwe
    263,

    # Somalia
    252,

    # South Sudan
    211,

    # Tunisia
    216,

    # Ukraine
    380,

    # Belarus
    375,

    # Central African Republic
    236,
)
